services:
  - type: web
    name: outlook-graphspy
    runtime: python
    plan: free
    buildCommand: pip install .
    startCommand: graphspy -i 0.0.0.0 -p $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MS_TENANT_ID
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_REDIRECT_URI
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true

